services:
  - type: web
    name: options-selector
    runtime: python
    plan: free
    region: virginia
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind :$PORT --workers 4 dashboard:server